// src/pages/CreatePage.tsx

import  { useState, useEffect } from 'react';
import { useAccount, useWriteContract, useWaitForTransactionReceipt } from 'wagmi';
import { parseUnits } from 'viem';
import { useNavigate } from 'react-router-dom';

import { raindropContractAddress, raindropContractABI, erc20ABI } from '../contracts/info';

export function CreatePage() {
  const navigate = useNavigate();
    const { isConnected } = useAccount();
      const { data: hash, writeContract, isPending, error } = useWriteContract();

        // State for form inputs
          const [raindropId, setRaindropId] = useState('');
            const [tokenAddress, setTokenAddress] = useState('');
              const [totalAmount, setTotalAmount] = useState('');
                const [scheduledTime, setScheduledTime] = useState('');

                  // State to track the approval flow
                    const [isApproving, setIsApproving] = useState(false);

                      // Wagmi hook to wait for the transaction to be mined
                        const { isLoading: isConfirming, isSuccess: isConfirmed } = useWaitForTransactionReceipt({ hash });

                          const handleApprove = async () => {
                              if (!tokenAddress || !totalAmount) {
                                    alert("Please provide a token address and amount.");
                                          return;
                                              }
                                                  setIsApproving(true);
                                                      writeContract({
                                                            address: tokenAddress as `0x${string}`,
                                                                  abi: erc20ABI,
                                                                        functionName: 'approve',
                                                                              args: [
                                                                                      raindropContractAddress,
                                                                                              parseUnits(totalAmount, 18) // Assuming 18 decimals, adjust if needed
                                                                                                    ],
                                                                                                        });
                                                                                                          };

                                                                                                            const handleCreateRaindrop = () => {
                                                                                                                const timestamp = Math.floor(new Date(scheduledTime).getTime() / 1000);
                                                                                                                    writeContract({
                                                                                                                          address: raindropContractAddress,
                                                                                                                                abi: raindropContractABI,
                                                                                                                                      functionName: 'createRaindrop',
                                                                                                                                            args: [
                                                                                                                                                    raindropId,
                                                                                                                                                            tokenAddress as `0x${string}`,
                                                                                                                                                                    parseUnits(totalAmount, 18), // Assuming 18 decimals
                                                                                                                                                                            BigInt(timestamp)
                                                                                                                                                                                  ],
                                                                                                                                                                                      });
                                                                                                                                                                                        };
                                                                                                                                                                                          
                                                                                                                                                                                            // This effect watches for the approval transaction to succeed
                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                  if (isConfirmed && isApproving) {
                                                                                                                                                                                                        setIsApproving(false); // Reset approval state
                                                                                                                                                                                                              // Now that approval is confirmed, call the createRaindrop function
                                                                                                                                                                                                                    handleCreateRaindrop();
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                          }, [isConfirmed, isApproving]);

                                                                                                                                                                                                                            // This effect watches for the final creation transaction to succeed
                                                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                                                  if (isConfirmed && !isApproving) {
                                                                                                                                                                                                                                        alert("Raindrop created successfully!");
                                                                                                                                                                                                                                              navigate(`/raindrop/${raindropId}`); // Redirect to details page
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                    }, [isConfirmed, !isApproving]);

                                                                                                                                                                                                                                                      if (!isConnected) {
                                                                                                                                                                                                                                                          return <p>Please connect your wallet to create a raindrop.</p>;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                              const isLoading = isPending || isConfirming;

                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                          <h2>Create a New Raindrop</h2>
                                                                                                                                                                                                                                                                                <form onSubmit={(e) => { e.preventDefault(); handleApprove(); }}>
                                                                                                                                                                                                                                                                                        <div style={{ marginBottom: '1rem' }}>
                                                                                                                                                                                                                                                                                                  <label>Raindrop ID (a unique name)</label><br />
                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                                                    value={raindropId}
                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setRaindropId(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                        style={{ width: '400px', padding: '0.5rem' }}
                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ marginBottom: '1rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                            <label>Token Contract Address</label><br />
                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                              value={tokenAddress}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setTokenAddress(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ width: '400px', padding: '0.5rem' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginBottom: '1rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label>Total Amount to Distribute</label><br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={totalAmount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setTotalAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: '400px', padding: '0.5rem' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginBottom: '1rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>Scheduled Execution Time</label><br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="datetime-local"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={scheduledTime}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setScheduledTime(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ width: '400px', padding: '0.5rem' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" disabled={isLoading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {isLoading ? 'Processing...' : 'Approve & Create Raindrop'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error && <p style={{ color: 'red' }}>Error: {error.shortMessage}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                