// src/pages/DetailsPage.tsx

import { useParams, useNavigate } from 'react-router-dom';
import { useAccount, useContractRead, useWriteContract, useWaitForTransactionReceipt } from 'wagmi';
import { formatUnits } from 'viem';
import React, { useState, useEffect } from 'react';

import { raindropContractAddress, raindropContractABI } from '../contracts/info';
import './DetailsPage.css';

export function DetailsPage() {
  const { id: raindropId } = useParams(); // Get raindropId from URL
    const navigate = useNavigate();
      const { address } = useAccount();

        // State for participant management
          const [participantsToAdd, setParticipantsToAdd] = useState('');

            // Wagmi hook to read raindrop details
              const { data: details, isLoading: isLoadingDetails, refetch: refetchDetails } = useContractRead({
                  address: raindropContractAddress,
                      abi: raindropContractABI,
                          functionName: 'getRaindropDetails',
                              args: [raindropId!],
                                  enabled: !!raindropId, // Only run query if raindropId is available
                                    });
                                      
                                        // Wagmi hook for writing to the contract (execute, cancel, add participants)
                                          const { data: hash, writeContract, isPending, error } = useWriteContract();
                                            const { isLoading: isConfirming, isSuccess: isConfirmed } = useWaitForTransactionReceipt({ hash });

                                              // Effect to refetch data and show alerts after a transaction is confirmed
                                                useEffect(() => {
                                                    if (isConfirmed) {
                                                          alert("Transaction successful!");
                                                                refetchDetails(); // Refetch the details to get the latest status
                                                                    }
                                                                      }, [isConfirmed]);

                                                                        const handleExecute = () => {
                                                                            writeContract({
                                                                                  address: raindropContractAddress,
                                                                                        abi: raindropContractABI,
                                                                                              functionName: 'executeRaindrop',
                                                                                                    args: [raindropId!],
                                                                                                        });
                                                                                                          };

                                                                                                            const handleCancel = () => {
                                                                                                                writeContract({
                                                                                                                      address: raindropContractAddress,
                                                                                                                            abi: raindropContractABI,
                                                                                                                                  functionName: 'cancelRaindrop',
                                                                                                                                        args: [raindropId!],
                                                                                                                                            });
                                                                                                                                              };

                                                                                                                                                const handleAddParticipants = () => {
                                                                                                                                                    // Parse the text area content into an array of addresses
                                                                                                                                                        const addresses = participantsToAdd.split(/[\s,]+/).filter(addr => addr.startsWith('0x'));
                                                                                                                                                            if (addresses.length === 0) {
                                                                                                                                                                  alert("Please enter valid addresses.");
                                                                                                                                                                        return;
                                                                                                                                                                            }
                                                                                                                                                                                writeContract({
                                                                                                                                                                                      address: raindropContractAddress,
                                                                                                                                                                                            abi: raindropContractABI,
                                                                                                                                                                                                  functionName: 'addParticipants',
                                                                                                                                                                                                        args: [raindropId!, addresses],
                                                                                                                                                                                                            });
                                                                                                                                                                                                              };
                                                                                                                                                                                                                
                                                                                                                                                                                                                  if (isLoadingDetails) return <p>Loading details...</p>;
                                                                                                                                                                                                                    if (!details) return <p>Could not find details for raindrop: {raindropId}</p>;

                                                                                                                                                                                                                      const [host, token, totalAmount, scheduledTime, executed, cancelled, participantCount] = details;
                                                                                                                                                                                                                        const isHost = address === host;
                                                                                                                                                                                                                          const executionDate = new Date(Number(scheduledTime) * 1000);
                                                                                                                                                                                                                            const canExecute = !executed && !cancelled && new Date() > executionDate;

                                                                                                                                                                                                                              const isLoading = isPending || isConfirming;

                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                    <div className="detailsContainer">
                                                                                                                                                                                                                                          <h2>Raindrop: {raindropId}</h2>
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                      <div className="detailsGrid">
                                                                                                                                                                                                                                                              <div><strong>Status:</strong></div>
                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                {executed ? <span className="status executed">Executed</span> :
                                                                                                                                                                                                                                                                                           cancelled ? <span className="status cancelled">Cancelled</span> :
                                                                                                                                                                                                                                                                                                      <span className="status scheduled">Scheduled</span>}
                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                      <div><strong>Host:</strong></div>
                                                                                                                                                                                                                                                                                                                              <div>{host}</div>

                                                                                                                                                                                                                                                                                                                                      <div><strong>Token:</strong></div>
                                                                                                                                                                                                                                                                                                                                              <div>{token}</div>

                                                                                                                                                                                                                                                                                                                                                      <div><strong>Total Amount:</strong></div>
                                                                                                                                                                                                                                                                                                                                                              <div>{formatUnits(totalAmount, 18)}</div>

                                                                                                                                                                                                                                                                                                                                                                      <div><strong>Scheduled Time:</strong></div>
                                                                                                                                                                                                                                                                                                                                                                              <div>{executionDate.toLocaleString()}</div>
                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                              <div><strong>Participants:</strong></div>
                                                                                                                                                                                                                                                                                                                                                                                                      <div>{participantCount.toString()}</div>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                  {isHost && !executed && !cancelled && (
                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="managementSection">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>Manage Raindrop</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="actionButtons">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={handleExecute} disabled={!canExecute || isLoading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {isLoading ? 'Processing...' : 'Execute Raindrop'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={handleCancel} disabled={isLoading} className="cancelButton">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isLoading ? 'Processing...' : 'Cancel Raindrop'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {!canExecute && <small>You can execute this raindrop after the scheduled time has passed.</small>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="addParticipants">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h4>Add Participants</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rows={5}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Paste addresses here, separated by spaces or commas."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={participantsToAdd}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setParticipantsToAdd(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={handleAddParticipants} disabled={isLoading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {isLoading ? 'Processing...' : 'Add Participants'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error && <p className="error">Error: {error.shortMessage}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }